- name: ec2 creation
  hosts: localhost
  connection: local
  vars:
    subnet_id: "subnet-03f6a20a70a34abc8"
    sg_id: "sg-0670763c62c77ba9b"
    ami_id: "ami-09c813fb71547fc4f"

    instances:
    - mysql

    zone: mxyz.shop

  tasks:
  - name: Install boto3 using pip
    ansible.builtin.pip:
      name: 
      - boto3

      - botocore
      executable: pip3.9
  
  

  - name: create ec2 for mysql
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro" 
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances_info
  
  - name: print the ec2-info
    ansible.builtin.debug:
      msg: "{{ ec2_instances_info }}"

  - name: create record
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private }}"
      wait: true
      overwrite: true
    loop: "{{ ec2-instances-info.}}"
