- name: backend module
  hosts: backend
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: mysql.mxyz.shop


  tasks:
    - name: disable defaut nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    
    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: ansible to install pymysql
      ansible.builtin.pip:
        name:
        - PyMySQL
        - cryptography
        executable: pip3.9

    - name: adding expense user by ansible module
      ansible.builtin.user:
        name: expense

    - name: create app directory by ansible file module
      ansible.builtin.file:
        path: /app
        state: directory

    - name: downlaod code from repo
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: extracting backend code to /app directory
      ansible.builtin.unarchive: 
        src: /tmp/backend.zip # by default ansible thinks its in ansible server
        dest: /app
        remote_src: yes

    - name: install dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
      
    - name: copy backend service to backend service to systemd/system
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: import mysql data
      community.mysql.mysql_db:
        login_host: "{{ login_host }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        target: /app/schema/backend.sql
        name: all
        state: dump
