- name: frontend module
  hosts: frontend
  become: yes

  tasks:
  - name: nginx installtion 
    ansible.builtin.package:
      name: nginx
      state: present
      enabled: yes
  
  - name: remove html content from nginx path
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download the front code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: extract the code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip #by default ansible thinks this is in ansible server
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy expense.conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted 

