- name: mysql module
  hosts: mysql
  become: yes
  tasks:
  - name: install MYSQL server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start MYSQL and enable item
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
      