- name: mysql module

  hosts: mysql

  become: yes

  vars:
    login_password: "ExpenseApp@1"
    login_host: "172.31.1.78"

  tasks:
    - name: install pymysql
      ansible.builtin.pip:
        name:
        - PyMySQL
        executable: pip3.9          

    - name: install mysql-server
      ansible.builtin.package:
        name: mysql-server
        state: present
    
  
    - name: start mysql-server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: connect mysql server
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ login_password }}"
        login_host: "{{ login_host }}"

