- name: mysql module

  hosts: mysql

  become: yes

  vars:
    

  tasks:
    - name: install mysql-server
      ansible.builtin.package:
        name: mysql-server
        state: present
    
  tasks:
    - name: start mysql-server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes