- name: mysql configuartion
  hosts: mysql
  become: yes
  tasks:
  - name: mysql installation
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: start mysql
    ansible.builtin.service:
      name: start mysqld
      state: started
      enabled: yes

