- name: mysql configuartion
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: mysql.mxyz.shop
  tasks:
  - name: mysql installation
    ansible.builtin.package:
      name: mysql-server
      state: present
  # - name: start mysql
  #   ansible.builtin.service:
  #     name: start mysqld
  #     state: restarted

  - name: connect mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
    register: mysql_info

  - name: print mysql mysql_info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"